### ISSUE TITLE
I just wanted to add the logos of the social in place of just simple text which might be attractive.

### ISSUE THREAD

**Issue by mnik7044** [vaibhavx42/Page-Pal#4]
Please assign this issue to me.

**Comment by vaibhavx42** [comment]
- Sure @mnik7044 you can work on this.
- Please keep title short and use the comment portion to describe the change .

**Comment by mnik7044** [comment]
I will make sure to keep that in mind

**Comment by mnik7044** [comment]
Hey @vaibhavx42 I opened a pr after changing the texts into logos please review and merge it.
